import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { VisitModel } from 'src/app/model/model';
import { doctorDetails } from 'src/config/constant';
import { getCacheData } from 'src/app/utils/utility-functions';
import { CoreService } from 'src/app/services/core/core.service';
import {
  ComplaintDetail, DetailRow, DocItem, Patient, PastVisit,
  SectionNavItem, SymptomGroup, TimelineGroup, VitalCell
} from './visit-summary-v2.models';
import { CurrentVisitData, VisitSummaryV2Service } from './visit-summary-v2.service';

@Component({
  selector: 'app-visit-summary-v2',
  templateUrl: './visit-summary-v2.component.html',
  styleUrls: ['./visit-summary-v2.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class VisitSummaryV2Component implements OnInit {
  visitId = '';

  topTabs = ['Current visits', 'Doctor\'s Note'];
  activeTopTab = 'Current visits';

  visitNoteStarted = false;

  get visibleTopTabs(): string[] {
    return this.visitNoteStarted
      ? this.topTabs
      : this.topTabs.filter(t => t !== 'Doctor\'s Note');
  }

  visitScopeTabs = ['Current visits', 'Past Visits'];
  activeVisitScope = 'Current visits';

  sections: SectionNavItem[] = [
    { key: 'consultation', label: 'Consultation details', icon: 'assets/svgs/consultation-details.svg' },
    { key: 'checkup', label: 'Check-up reason', icon: 'assets/svgs/check-up-reason.svg' },
    { key: 'history', label: 'Medical history', icon: 'assets/svgs/medical-history.svg' },
    { key: 'vitals', label: 'Vitals', icon: 'assets/svgs/vitals.svg' },
    { key: 'physical', label: 'Physical examination', icon: 'assets/svgs/physical-examination.svg' },
    { key: 'documents', label: 'Additional documents', icon: 'assets/svgs/additional-documents.svg' },
    { key: 'refer', label: 'Refer to specialist', icon: 'assets/svgs/refer-to-specialist.svg' }
  ];
  activeSection = 'consultation';

  doctorNoteNav: SectionNavItem[] = [
    { key: 'dn-interaction', label: 'Patient interaction', icon: 'assets/svgs/patient-interaction.svg' },
    { key: 'dn-diagnosis', label: 'Diagnosis', icon: 'assets/svgs/diagnosis.svg' },
    { key: 'dn-note', label: 'Note', icon: 'assets/svgs/note.svg' },
    { key: 'dn-medication', label: 'Medication', icon: 'assets/svgs/medication.svg' },
    { key: 'dn-advice', label: 'Advice', icon: 'assets/svgs/advice.svg' },
    { key: 'dn-test', label: 'Test', icon: 'assets/svgs/test.svg' },
    { key: 'dn-referral', label: 'Referral-Out', icon: 'assets/svgs/referal.svg' },
    { key: 'dn-followup', label: 'Follow-up', icon: 'assets/svgs/follow-up.svg' },
    { key: 'dn-documents', label: 'Additional documents', icon: 'assets/svgs/additional-document-purple.svg' }
  ];

  patient: Patient | null = null;
  consultationDetails: DetailRow[] = [];
  chiefComplaints: string[] = [];
  complaintDetails: ComplaintDetail[] = [];
  associatedSymptoms: SymptomGroup[] = [];
  patientHistory: DetailRow[] = [];
  familyHistory: DetailRow[] = [];
  vitals: VitalCell[] = [];
  generalExams: DetailRow[] = [];
  eyeImages: string[] = [];
  abdomenFindings: string[] = [];
  documents: DocItem[] = [];
  specializations: string[] = [];

  chwNote = 'This history note and physical exam note was generated by a community health worker with the support of the Intelehealth mobile application and Ayu, a digital assistant. It collects only preliminary findings and may not gather all of the patient\'s clinical information, especially sensitive information or complex physical exam information which is hard for the health worker to collect. Please verify crucial clinical information and collect any additional information you require by speaking with the patient directly.';

  activePastVisitKey = '';

  pastVisitsTimeline: TimelineGroup[] = [];

  get activePastVisit(): PastVisit | undefined {
    for (const group of this.pastVisitsTimeline) {
      const found = group.visits.find(v => v.key === this.activePastVisitKey);
      if (found) { return found; }
    }
    return this.pastVisitsTimeline[0]?.visits[0];
  }

  visit!: VisitModel;
  visitNoteExists = false;
  visitNoteUuid = '';
  patientUuid = '';
  private providerUuid = '';

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private coreService: CoreService,
    private v2Service: VisitSummaryV2Service
  ) {}

  ngOnInit(): void {
    this.visitId = this.route.snapshot.paramMap.get('id') || '';
    this.providerUuid = getCacheData(true, doctorDetails.PROVIDER)?.uuid || '';
    this.loadVisit();
  }

  private loadVisit(): void {
    if (!this.visitId) { return; }
    this.v2Service.loadCurrentVisit(this.visitId).subscribe((data: CurrentVisitData) => {
      if (data) { this.applyCurrentVisit(data); }
    });
  }

  private applyCurrentVisit(data: CurrentVisitData): void {
    this.visit = data.visit;
    this.visitNoteExists = data.visitNoteExists;
    this.visitNoteUuid = data.visitNoteUuid;
    this.patientUuid = data.patientUuid;
    this.visitNoteStarted = data.visitNoteExists;
    this.specializations = data.specializations;
    this.patient = data.patient;
    this.consultationDetails = data.consultationDetails;
    this.chiefComplaints = data.chiefComplaints;
    this.complaintDetails = data.complaintDetails;
    this.associatedSymptoms = data.associatedSymptoms;
    this.patientHistory = data.patientHistory;
    this.familyHistory = data.familyHistory;
    this.vitals = data.vitals;
    this.generalExams = data.generalExams;
    this.abdomenFindings = data.abdomenFindings;
    this.eyeImages = data.eyeImages;
    this.documents = data.documents;
    this.loadPastVisits();
  }

  private loadPastVisits(): void {
    if (!this.patientUuid || !this.visitId) { return; }
    this.v2Service.loadPastVisits(this.patientUuid, this.visitId).subscribe((timeline: TimelineGroup[]) => {
      this.pastVisitsTimeline = timeline;
      const first = timeline[0]?.visits[0];
      if (first) { this.activePastVisitKey = first.key; }
    });
  }

  setTopTab(tab: string): void {
    this.activeTopTab = tab;
    const id = tab === 'Doctor\'s Note' ? 'section-doctor-note' : 'section-consultation';
    const el = document.getElementById(id);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }

  setVisitScope(tab: string): void {
    this.activeVisitScope = tab;
  }

  selectPastVisit(key: string): void {
    this.activePastVisitKey = key;
  }

  selectSection(key: string): void {
    this.activeSection = key;
    const el = document.getElementById('section-' + key);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }

  startVisitNote(): void {
    if (!this.visit) { return; }
    this.v2Service.createVisitNote(this.visit, this.providerUuid).subscribe(() => {
      this.visitNoteExists = true;
      this.visitNoteStarted = true;
      this.loadVisit();
      setTimeout(() => this.setTopTab('Doctor\'s Note'));
    });
  }

  reassignVisit(speciality: string): void {
    if (!this.visit) { return; }
    if (this.visitNoteExists) {
      this.coreService.showToast('warning', 'Can\'t refer, visit note already exists for this visit!', 'Can\'t refer', 'warning-visit-note-exists-toast');
      return;
    }
    if (!speciality) {
      this.coreService.showToast('warning', 'Please select specialization', 'Invalid!', 'warning-select-specialization-toast');
      return;
    }
    this.coreService.openConfirmationDialog({
      confirmationMsg: 'Are you sure to re-assign this visit to another doctor?',
      cancelBtnText: 'Cancel',
      confirmBtnText: 'Confirm'
    }).afterClosed().subscribe((confirmed: boolean) => {
      if (!confirmed) { return; }
      this.v2Service.reassignSpeciality(this.visit, speciality, this.providerUuid).subscribe((res) => {
        if (res) {
          this.router.navigate(['/dashboard']);
          this.coreService.showToast('success', 'Visit has been re-assigned to the another speciality doctor successfully.', 'Visit Re-assigned!', 'visit-reassigned-toast');
        }
      });
    });
  }
}
