
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: false,
    base: 'https://dev.intelehealth.org',
    baseURL: 'https://dev.intelehealth.org/openmrs/ws/rest/v1',
    baseURLCoreApp: 'https://dev.intelehealth.org/openmrs/coreapps/diagnoses',
    baseURLLegacy: 'https://dev.intelehealth.org/openmrs',
    mindmapURL: 'https://dev.intelehealth.org:3004/api',
    notificationURL: 'https://dev.intelehealth.org:3004/notification',
    socketURL: 'https://dev.intelehealth.org:3004',
    captchaSiteKey: '6Lc3ZUYoAAAAAPRXxpFBC3zGHjqfbgbNZkd7DVBl',
    firebase: {
        apiKey: 'AIzaSyDkU15rxve37d9hu_4y0lUNOfrUX6iSpUI',
        authDomain: 'intelehealth-webapp.firebaseapp.com',
        projectId: 'intelehealth-webapp',
        storageBucket: 'intelehealth-webapp.appspot.com',
        messagingSenderId: '246647122371',
        appId: '1:246647122371:web:c45944219d1f37bf30b576',
    },
    webrtcSdkServerUrl: 'wss://dev.intelehealth.org:9090',
    webrtcTokenServerUrl: 'https://dev.intelehealth.org:3000/',
    siteKey: '6Lc3ZUYoAAAAAPRXxpFBC3zGHjqfbgbNZkd7DVBl',
    externalPrescriptionCred: 'c3lzbnVyc2U6TnVyc2VAMTIz',
    vapidPublicKey: 'BCGfng5flfhjlqR_imzFXwHGeEMBA6AzFVAex7sPLDbsMCn_IMKtQmI9TDnmP6raxmPcBcnoKO_AHKaLtctsIjg',
    authGatwayURL: 'https://dev.intelehealth.org:3030/v2/',
    showCaptcha: true,
    recordsPerPage: 1000
  };
