/* tslint:disable */
// @ts-nocheck
const { writeFile, existsSync, mkdirSync } = require('fs');
const { argv } = require('yargs');

require('dotenv').config();
const environment = argv.environment;


function writeFileUsingFS(targetPath, environmentFileContent) {
  writeFile(targetPath, environmentFileContent, function (err) {
    if (err) {
      console.log(err);
    }
    if (environmentFileContent !== '') {
      console.log(`wrote variables to ${targetPath}`);
    }
  });
}


// Providing path to the `environments` directory
const envDirectory = './src/environments';

// creates the `environments` directory if it does not exist
if (!existsSync(envDirectory)) {
  mkdirSync(envDirectory);
}

//creates the `environment.prod.ts` and `environment.ts` file if it does not exist
writeFileUsingFS('./src/environments/environment.prod.ts', '');
writeFileUsingFS('./src/environments/environment.ts', '');


// Checks whether command line argument of `prod` was provided signifying production mode
const isProduction = environment === 'prod';

// choose the correct targetPath based on the environment chosen
const targetPath = isProduction
  ? './src/environments/environment.prod.ts'
  : './src/environments/environment.ts';

const fallback = {
  BASE: '',
  BASE_URL: '/openmrs/ws/rest/v1',
  BASE_URL_CORD_APP: '/openmrs/coreapps/diagnoses',
  BASE_URL_LEGACY: 'https://intelehealth-prod-master-new.mpower-social.com/openmrs/',
  MIND_MAP_URL: 'https://intelehealth-prod-master-new.mpower-social.com:3004/api',
  CONFIG_URL: 'https://intelehealth-prod-master-new.mpower-social.com:4004/api',
  NOTIFICATION_URL: 'https://intelehealth-prod-master-new.mpower-social.com:3004/notification',
  SOCKET_URL: 'https://intelehealth-prod-master-new.mpower-social.com:3004',
  WEB_RTC_SDK_SERVER_URL: 'wss://intelehealth-prod-master-new.mpower-social.com:9090',
  WEB_RTC_TOKEN_SERVER_URL: 'https://intelehealth-prod-master-new.mpower-social.com:3030',
  AUTH_GATE_WAY_URL: 'https://intelehealth-prod-master-new.mpower-social.com:3030/v2/',
  VAPID_PUBLIC_KEY: 'BACBe2a-6cpm7RESlWn4Ln1ofnSQxbeedmg5kuPq9CqJ8hX22cfFUGaU5R5E9bM8w-7M_NDWBPOz3zVzfKP0mm4',
  CAPTCHA_SITE_KEY: '6LdbXvApAAAAANFjXjgOQnaX7ESR2IBPIOO9KpvS',
  SITE_KEY: '6Lf_UPEpAAAAAJesudYovsIWUXdpCtCGUtphyqIZ',
  SHOW_CAPTCHA: 'false',
  FIREBASE_API_KEY: 'AIzaSyDCC1JLFTVhM5smLy5BTn96dhiOj_gSUWQ',
  FIREBASE_AUTH_DOMAIN: 'intelhealth-mpower.firebaseapp.com',
  FIREBASE_PROJECT_ID: 'intelhealth-mpower',
  FIREBASE_STORAGE_BUCKET: 'intelhealth-mpower.appspot.com',
  FIREBASE_MESSAGING_SENDER_ID: '971382487208',
  FIREBASE_APP_ID: '1:971382487208:web:13f83dac2ff14f54bdaa9d',
  BRAND_NAME: '',
  RECORDS_PER_PAGE: '10',
  GAMEASUREMENTID: '',
  PAGERDUTY_URL: '',
  EXTERNAL_PRESCRIPTION_CRED: '',
  ABHA_URL: '',
  ABHA_ENABLED: 'false',
  FEATURES_LIST: '["followUpType", "tnmStaging", "referralFacility", "priorityOfReferral", "visitFollowUp", "visitNotes"]'
};

function getEnv(key) {
  return process.env[key] ?? fallback[key] ?? '';
}

function envString(key) {
  return JSON.stringify(getEnv(key));
}

function envBoolean(key) {
  return String(getEnv(key)).toLowerCase() === 'true';
}

function envNumber(key) {
  const value = Number(getEnv(key));
  return Number.isNaN(value) ? Number(fallback[key]) : value;
}

function envJson(key) {
  try {
    return JSON.stringify(JSON.parse(getEnv(key)));
  } catch (error) {
    return JSON.stringify(JSON.parse(fallback[key]));
  }
}

let showCaptcha = envBoolean('SHOW_CAPTCHA');

if (environment === 'test') {
  showCaptcha = false;
}
const recordsPerPage = envNumber('RECORDS_PER_PAGE');
//actual content to be compiled dynamically and pasted into respective environment files
const environmentFileContent = `
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    PRODUCTION: ${isProduction},
    production: ${isProduction},

    BASE: ${envString('BASE')},
    base: ${envString('BASE')},

    BASE_URL: ${envString('BASE_URL')},
    baseURL: ${envString('BASE_URL')},

    BASE_URL_CORD_APP: ${envString('BASE_URL_CORD_APP')},
    baseURLCoreApp: ${envString('BASE_URL_CORD_APP')},
    baseURLLegacy: ${envString('BASE_URL_LEGACY')},
    BASE_URL_LEGACY: ${envString('BASE_URL_LEGACY')},

    MIND_MAP_URL: ${envString('MIND_MAP_URL')},
    mindmapURL: ${envString('MIND_MAP_URL')},

    PAGERDUTY_URL: ${envString('PAGERDUTY_URL')},
    pagerdutyURL: ${envString('PAGERDUTY_URL')},

    CONFIG_URL: ${envString('CONFIG_URL')},
    configURL: ${envString('CONFIG_URL')},
    configPublicURL: ${envString('CONFIG_PUBLIC_URL') !== '""' ? envString('CONFIG_PUBLIC_URL') : envString('CONFIG_URL')},

    ABHA_URL: ${envString('ABHA_URL')},
    abhaURL: ${envString('ABHA_URL')},

    NOTIFICATION_URL: ${envString('NOTIFICATION_URL')},
    notificationURL: ${envString('NOTIFICATION_URL')},

    SOCKET_URL: ${envString('SOCKET_URL')},
    socketURL: ${envString('SOCKET_URL')},

    CAPTCHA_SITE_KEY: ${envString('CAPTCHA_SITE_KEY')},
    captchaSiteKey: ${envString('CAPTCHA_SITE_KEY')},
    SITE_KEY: ${envString('SITE_KEY')},
    siteKey: ${envString('SITE_KEY')},
    SHOW_CAPTCHA: ${showCaptcha},
    showCaptcha: ${showCaptcha},

    firebase: {
        apiKey: ${envString('FIREBASE_API_KEY')},
        authDomain: ${envString('FIREBASE_AUTH_DOMAIN')},
        projectId: ${envString('FIREBASE_PROJECT_ID')},
        storageBucket: ${envString('FIREBASE_STORAGE_BUCKET')},
        messagingSenderId: ${envString('FIREBASE_MESSAGING_SENDER_ID')},
        appId: ${envString('FIREBASE_APP_ID')},
    },

    FIREBASE_API_KEY: ${envString('FIREBASE_API_KEY')},
    FIREBASE_AUTH_DOMAIN: ${envString('FIREBASE_AUTH_DOMAIN')},
    FIREBASE_PROJECT_ID: ${envString('FIREBASE_PROJECT_ID')},
    FIREBASE_STORAGE_BUCKET: ${envString('FIREBASE_STORAGE_BUCKET')},
    FIREBASE_MESSAGING_SENDER_ID: ${envString('FIREBASE_MESSAGING_SENDER_ID')},
    FIREBASE_APP_ID: ${envString('FIREBASE_APP_ID')},

    WEB_RTC_SDK_SERVER_URL: ${envString('WEB_RTC_SDK_SERVER_URL')},
    webrtcSdkServerUrl: ${envString('WEB_RTC_SDK_SERVER_URL')},

    WEB_RTC_TOKEN_SERVER_URL: ${envString('WEB_RTC_TOKEN_SERVER_URL')},
    webrtcTokenServerUrl: ${envString('WEB_RTC_TOKEN_SERVER_URL')},

    AUTH_GATE_WAY_URL: ${envString('AUTH_GATE_WAY_URL')},
    authGatwayURL: ${envString('AUTH_GATE_WAY_URL')},

    VAPID_PUBLIC_KEY: ${envString('VAPID_PUBLIC_KEY')},
    vapidPublicKey: ${envString('VAPID_PUBLIC_KEY')},

    externalPrescriptionCred: ${envString('EXTERNAL_PRESCRIPTION_CRED')},
    recordsPerPage: ${recordsPerPage},
    abhaEnabled: ${envBoolean('ABHA_ENABLED')},
    brandName: ${envString('BRAND_NAME')},
    featureList: ${envJson('FEATURES_LIST')},
    gaMeasurementId: ${envString('GAMEASUREMENTID')},

    FEATURES_LIST: ${envJson('FEATURES_LIST')}
  };
`;

writeFileUsingFS(targetPath, environmentFileContent); // appending data into the target file

/* tslint:enable */
