import { Component, OnInit } from "@angular/core";

@Component({
  selector: "app-interaction-note-v4",
  templateUrl: "./interaction-note-v4.component.html",
  styleUrls: ["./interaction-note-v4.component.scss"],
})
export class InteractionNoteV4Component implements OnInit {
  notes: any =
    "This history note and physical exam note was generated by a community health worker with the support of the Intelehealth mobile application and Ayu, a digital assistant. It collects only preliminary findings and may not gather all of the patient's clinical information, especially sensitive information or complex physical exam information which is hard for the health worker to collect. Please verify crucial clinical information and collect any additional information you require by speaking with the patient directly.";

  constructor() {}

  ngOnInit(): void {}
}
