
const fs = require('node:fs');
const path = require('node:path');
const dotenv = require('dotenv');

const projectRoot = path.resolve(__dirname, '..');

const modeFlag = process.argv.find((a) => a.startsWith('--mode='));
const explicitMode = modeFlag ? modeFlag.split('=')[1] : null;
const mode =
  explicitMode || (process.env.NODE_ENV === 'production' ? 'production' : 'development');

const candidates = [
  path.join(projectRoot, `.env.${mode}.local`),
  path.join(projectRoot, `.env.${mode}`),
  path.join(projectRoot, '.env.local'),
  path.join(projectRoot, '.env'),
];

const loaded = [];
for (const file of candidates) {
  if (fs.existsSync(file)) {
    dotenv.config({ path: file, override: false });
    loaded.push(path.basename(file));
  }
}

if (loaded.length === 0) {
  console.error(
    '[set-env] No .env file found. Copy .env.example to .env and fill in values before running.'
  );
  process.exit(1);
}

const required = [
  'CLIENT',
  'EZAZI_BASE_URL',
  'NEPAL_BASE_URL',
  'EZAZI_CAPTCHA_SITE_KEY',
  'NEPAL_CAPTCHA_SITE_KEY',
  'EXTERNAL_PRESCRIPTION_CRED',
  'VAPID_PUBLIC_KEY',
  'RECORDS_PER_PAGE',
];

const missing = required.filter((key) => !process.env[key] || process.env[key].trim() === '');
if (missing.length > 0) {
  console.error(`[set-env] Missing required env vars: ${missing.join(', ')}`);
  console.error('[set-env] See .env.example for the full list.');
  process.exit(1);
}

const cfg = {
  client: process.env.CLIENT,
  ezaziBaseUrl: process.env.EZAZI_BASE_URL,
  nepalBaseUrl: process.env.NEPAL_BASE_URL,
  ezaziCaptchaSiteKey: process.env.EZAZI_CAPTCHA_SITE_KEY,
  nepalCaptchaSiteKey: process.env.NEPAL_CAPTCHA_SITE_KEY,
  externalPrescriptionCred: process.env.EXTERNAL_PRESCRIPTION_CRED,
  vapidPublicKey: process.env.VAPID_PUBLIC_KEY,
  recordsPerPage: Number(process.env.RECORDS_PER_PAGE),
};

const banner = `// AUTO-GENERATED by scripts/set-env.js — DO NOT EDIT.
// Source: ${loaded.join(', ')}
`;

const body = `export const envConfig = ${JSON.stringify(cfg, null, 2)} as const;

export type Client = 'ezazi' | 'nepal';
`;

const outFile = path.join(projectRoot, 'src/environments/environment.generated.ts');
fs.writeFileSync(outFile, `${banner}\n${body}`);

console.log(`[set-env] Wrote ${path.relative(projectRoot, outFile)} (mode=${mode}, loaded=${loaded.join(', ')})`);
