// export default [
//   "Albendazole Tablets 400mg",
//   "Amlodipine Tablets 5 mg",
//   "Amoxycillin Capsules 500 mg",
//   "Amoxycillin Capsules 250mg",
//   "Ascorbic Acid Tablets(Chewable)",
//   "Atenolol Tablets 50 mg",
//   "Bisacodyl Tablet 5 mg",
//   "Calcium gluconate Tablet 500 mg",
//   "Chloroquine phosphateTablet 250 mg",
//   "Chlorpheniramine Maleate Tablets 4 mg",
//   "Clotrimazole Vaginal Tablet 100 mg",
//   "Dexamethasone Tablet 0.5 mg",
//   "Diclofenac Sodium Tablets 50 mg",
//   "Dicyclomine Tablets 20 mg",
//   "Domperidone Tablets 10 mg",
//   "Enalapril Maleate Tablets 5 mg",
//   "Etopyllin with theophylline tablet",
//   "Ferrous salt 20 mg + Folic acid 100 mcg Tablet",
//   "Ferrous salt 100 mg + Folic acid 500 mcg Tablet",
//   "Folic Acid Tablets 5mg",
//   "Ibuprofen Tablets 400mg",
//   "Metformin HCL Tablets 500mg",
//   "Metronidazole Tablets 400mg",
//   "Metronidazole Tablet 200mg",
//   "Norfloxacin Tablets 400mg",
//   "Paracetamol Tablets 500mg",
//   "Primaquine Phosphate Tablets 2.5mg",
//   "Primaquine Phosphate Tablets 7.5mg",
//   "Salbutamol Tablet 4 mg",
//   "Vitamin A Capsules",
//   "Vitamin B Complex Tablets (Therapeutic)",
//   "Azithromycin Tablet 500 mg",
//   "Cefixime Tablet 200 mg",
//   "Asprin (Acetylsalicylic acid) Tablet 75 mg",
//   "Clopidogrel Tablets 75mg",
//   "Zinc Sulphate Dispersible Tablets 20mg",
//   "Atorvastatin Tablet 40 mg",
//   "Bisacodyl Suppository 5 mg",
//   "Azithromycin Tablet 250 mg",
//   "Famotidine Tablets 40mg",
//   "Formoterol & Budesonide Rotacap 6 mcg+ 200 mcg 200mcg",
//   "Montelukast Sodium Tablet 10 mg",
//   "Paracetamol Tablet 650 mg",
//   "Labetalol Tablet 100 mg",
//   "Ferrous salt 60mg + Folic acid 500mcg",
//   "Tablet Diclofenac sodium",
//   "Injection Eteophylline & Theophylline",
//   "Injection Gentamicin Injection 80 mg/ml",
//   "Pralidoxime chloride Injection 25 mg/ml",
//   "Ringer lactate Injection",
//   "Sodium chloride injection",
//   "Sterile Water for Injection (5ml)",
//   "Vitamin B Complex Injection",
//   "Sodium Chloride Inj.(IV use) 100ml",
//   "Albendazole Oral liquid 200 mg/5 ml",
//   "Amoxycillin oral suspension",
//   "Betamethasone Valerate Cream 0.1%",
//   "Cholecalciferol Granules (Vitamin D3)",
//   "Ciprofloxacin Ophthalmic Solution",
//   "Clotrimazole Cream 1%",
//   "Vitamin A Solution Conc. 1 Lac IU/1ml, 100ml",
//   "Bottle Dextromethorphan Syrup 13.5 mg/5 ml",
//   "Domperidone Syrup",
//   "Framycetin Sulphate Skin Cream (30Gm Tube)",
//   "Glycerine Hydrogen peroxide Solution",
//   "Ibuprofen oral Suspension 100 mg/5 ml",
//   "Metronidazole Oral liquid 100 mg/5 ml",
//   "O.R.S.(W.H.O. Formula)",
//   "Paracetamol Syrup 125 mg/5ml",
//   "Povidone iodine Solution 5%",
//   "Povidine lodine (Ointment)",
//   "Povidone lodine Solution 5%W/V(1 Litre)",
//   "Salbutamol Nebulizer Solution",
//   "Salbutamol Syrup 2 mg/5 ml",
//   "Silver sulphadiazine Cream 1%",
//   "Calamine Lotion Neomycin",
//   "Bacitracin & Palymaxin B Oint.",
//   "Azithromycin Oral liquid 200mg/5ml",
//   "Levocetirizine Dihydrochloride Syrup",
//   "Lignocaine Hydrochloride Jelly",
//   "IRON FOLIC ACID (IFA) SYRUP",
//   "Alcoholic Rub Hand Disinfectant 500 ml",
//   "Calcium & Vitamin D3 Suspension 100 ml bottle",
//   "Cefixime syrup",
//   "Xylometazoline Nasal Drops 0.05%",
//   "Disposable Syringe 10 ml(Without Needle)",
//   "Sterile Hypodermic Syringe for Single use Size 2 ml(Without Needle)",
//   "Sterile Hypodermic Syringe for Single use Size: SML(Without Needle)",
//   "Plastic Bags(Yellow)",
//   "Small Plastic Bags(Red)",
//   "Small Plastic Bags(Black)",
//   "Small Surgical Rubber Gloves(Disposable) 6 Inch",
//   "Surgical Rubber Gloves(Disposable) 6.5 Inch",
//   "Surgical Rubber Gloves(Disposable) 7 Inch",
//   "Surgical Rubber Gloves (Disposable) 7.5 Inch",
//   "Surgical Rubber Gloves (Disposable) 8 Inch tab",
//   "metformin 500mg + tab glimeperide 2mg tab",
//   "metformin 500mg + tab glimeperide 1mg Glimepiride Tablet 2 mg",
//   "Metformin Hydrochloride Tablets 500 mg TAB",
//   "GLIPIZIDE 5MG",
//   "Tab Paracetamol 500mg",
//   "Tab Cetrizine 10mg",
//   "Tab Amoxicillin/clavulanic acid 875/125mg",
//   "Cap Omeprazole 20mg",
//   "Tab Dexamethasone 6mg",
//   "Tab Hydrocortisone 10mg",
//   "Tab Prednisolone 20mg",
//   "Tab Methylprednisolone 8mg",
//   "Tab Vitamin C 500mg",
//   "Cholecalciferol Grannules 6000IU",
//   "Tab Metformin 500mg",
//   "Tab Glimepride 2mg",
//   "Tab Glibenclamide 5mg",
//   "Tab Atenolol 50mg",
//   "Tab Amlodepine 5mg",
//   "Tab Enalapril 5mg",
//   "Tab Cefixime 200mg",
//   "Tab Azithromycin 250mg",
//   "Lactulose 250ml bottle",
//   "ORS 21gm sachet",
//   "Tab Doxycycline 100mg",
//   "Syrup Kesol 200ml bottle"
// ];

export default {
    earlyMorning: [
        '1 Glass of water with 1 tablespoon of Methi seeds [soaked overnight]',
        '1 Glass of water with 1 teaspoon of Methi seeds [soaked overnight]',
    ],
    breakfast: [
        'Tea with milk [no sugar]',
        'Milk [no sugar]',
        'Coffee [no sugar]',
        'Poha',
        'Vegetable poha',
        'Upma',
        'Vegetable upma',
        'Plain paratha [without oil]',
        'Paneer paratha',
        'Vegetable stuffed paratha [without oil]',
        'Daliya with milk [no sugar]',
        'Jowar with milk [no sugar]',
        'Oats with milk [no sugar]',
        'Curd',
        'Sabzi [Avoid potato, sweet potato, yam, corn]',
        'Herbal tea',
        'phulkas',
        'chapatti',
        'Idli',
        'Dosa',
        'Oats Dosa',
        'Rava Dosa',
        'Rava Idli',
        'Onion Tomato Uttappam',
        'sambhar',
        'Red chutney',
        'Besan Cheela',
        'Besan Cheela with vegetables',
        'Moong dal Cheela',
        'Moong dal Cheela with vegetables',
        'Cornflakes',
        'Oats',
        'egg [medium size]',
        'egg [without yellow part; medium size]',
        'Whole wheat bread',
        'Dhokla [2 big pieces]',
        'Fruit [Avoid banana, grapes, mango, cheeku, jackfruit]'
    ],
    midMorning: [
        'Fruit [Avoid banana, grapes, mango, cheeku, jackfruit]',
        'Buttermilk [No sugar]',
        'Egg [boiled medium size]',
        'Egg [boiled without yellow part; medium size]',
        'Nuts [Avoid raisins/ dates/ cashewnuts]',
        'Cucumber sticks',
        'sprouts with onion and tomato'
    ],
    lunch: [
        'Chapatti',
        'phulkas',
        'parataha without oil',
        'Vegetable paratha without oil [Avoid carrot, potato, corn]',
        'Thepla [medium size]',
        'Jowar bhakri',
        'Bajra bhakri',
        'Soya bhakri',
        'Ragi Bhakri',
        'Jowar + Wheat chapatti [1:1]',
        'Bajra + Wheat chapatti [1:1]',
        'Ragi + Wheat chapatti [1:1]',
        'Besan Cheela',
        'Moong dal cheela',
        'Paneer paratha without oil',
        'Sabzi [Avoid potato, corn, yam, sweet potato, carrot, beetroot]',
        'Curd',
        'Buttermilk',
        'Rice',
        'Dal',
        'Kadhi',
        'Khichdi',
        'Moong Dal Pulao',
        'Vegetble pulao',
        'Vegetable khichdi',
        'Moong Dal',
        'Tuur Dal',
        'Beans',
        'Chicken Biryani',
        'Chicken piece [Medium piece]',
        'Fish [medium piece]',
        'Mutton [Avoid beef]',
        'Sprouts',
        'Rajma',
        'Chole',
        'White beans',
        'Red Beans',
        'Salad',
        'Sprouts salad',
        'Cabbage salad',
        'Chicken salad with vegetables',
        'Paneer gravy',
        'Roasted paneer',
        'Paneer salad',
        'Beans salad',
        'Soy Chapatti'
    ],
    eveningSnack: [
        'Roasted Chana',
        'Roasted Makhana',
        'Poha chevda',
        'Khakra [non fried]',
        'Bajra chivda',
        'Sprouts salad',
        'Boiled sprouts',
        'Jowar with milk',
        'Bajra with milk',
        'Oats with milk',
        'Vegetable poha',
        'Vegetable Upma',
        'Tea with milk [No Sugar] [without sugar]',
        'Coffee [without sugar]',
        'Herbal tea [without sugar]',
        'Milk [without sugar]',
    ],
    dinner: [
        'Chapatti',
        'phulkas',
        'parataha without oil',
        'Vegetable paratha without oil [Avoid carrot, potato, corn]',
        'Thepla [medium size]',
        'Jowar bhakri',
        'Bajra bhakri',
        'Soya bhakri',
        'Ragi Bhakri',
        'Jowar + Wheat chapatti [1:1]',
        'Bajra + Wheat chapatti [1:1]',
        'Ragi + Wheat chapatti [1:1]',
        'Besan Cheela',
        'Moong dal cheela',
        'Paneer paratha without oil',
        'Sabzi [Avoid potato, corn, yam, sweet potato, carrot, beetroot]',
        'Curd',
        'Buttermilk',
        'Brown Rice',
        'Dal',
        'Kadhi',
        'Khichdi',
        'Moong Dal Pulo',
        'Vegetble pulao',
        'Vegetable khichdi',
        'Moong Dal',
        'Tuur Dal',
        'Beans',
        'Chicken Biryani',
        'Chicken [Medium piece]',
        'Fish [medium piece]',
        'Mutton [Avoid beef]',
        'Sprouts',
        'Rajma',
        'Chole',
        'White beans',
        'Red Beans',
        'Salad',
        'Sprouts salad',
        'Cabbage salad',
        'Chicken salad with vegetables',
        'Paneer gravy',
        'Paneer roasted',
        'Paneer salad',
        'Beans salad',
        'Soy Chapatti'
    ],
    bedTime: [
        'Milk [no sugar]',
        'Protein supplement',
        'Fruit [Avoid banana, grapes, mango, cheeku, jackfruit]',
        'Nuts [Avoid raisins/ dates/ cashewnuts]',
        '1 Glass of water with 1 tablespoon of Methi seeds [soaked overnight]',
        '1 Glass of water with 1 teaspoon of Methi seeds [soaked overnight]'
    ]
}