export default [
"Acetylsalicylic acid (Aspirin) Tablet 75 mg",
"Albendazole Tablet 400 mg",
"Albendazole Oral Liquid 200 mg/5 ml",
"Ambroxol* Oral Liquid 30 mg/5 ml",
"Ambroxol* Oral Drops 7.5 mg/1 ml",
"Ambroxol+Levosalbutamol+Guaifensin* Oral Liquid (30 mg+1 mg+50 mg/5 ml)",
"Ambroxol+Levosalbutamol+Guaifensin* Oral Drops (7.5 mg+0.25 mg+12.5 mg/5 ml)",
"Amlodipine Tablet 5 mg",
"Amoxicillin Capsule 250 mg",
"Amoxicillin Capsule 500 mg",
"Amoxicillin Oral liquid 250 mg/5 ml",
"Amoxicillin + Clavulanic acid Tablet 625 mg",
"Amoxicillin + Clavulanic acid Oral Liquid 228.5 mg/5 ml",
"Atorvastatin Tablet 10 mg",
"Azithromycin Tablet 500 mg",
"Azithromycin Oral Liquid 200 mg/5 ml",
"B-Complex (Multivitamin) Capsule",
"Betamethasone Valerate Cream 0.05%",
"Bevon* (Multivitamin) Oral Liquid",
"Bevon* (Multivitamin) Oral Drops",
"Calamine Lotion",
"Calcium Carbonate Tablet 625 mg",
"Calcimax P* Oral Liquid 150 mg/5 ml",
"Cefixime Oral Liquid 50 mg/5 ml",
"Cefixime Tablet 100 mg",
"Cefixime Tablet 200 mg",
"Cetirizine Oral Liquid 5 mg/5 ml",
"Cetirizine Tablet 10 mg",
"Chloroquine Oral liquid 50 mg/5 ml",
"Chloroquine Tablet 150 mg",
"Chlorpheniramine Maleate+Phenylephrine* Oral Drops (2 mg+5 mg/1 ml)",
"Cholecalciferol Oral Liquid 400 IU/1 ml",
"Cholecalciferol Oral Sachet 1000 IU",
"Ciprofloxacin Eye/Ear Drops 0.3%",
"Ciprofloxacin Tablet 250 mg",
"Ciprofloxacin Tablet 500 mg",
"Clotrimazole Ear Drops 1%",
"Clotrimazole Lotion 1%",
"Clotrimazole Cream 1%",
"Clotrimazole Pessary (Vaginal Tablet) 100 mg",
"Clotrimazole Mouth Paint 1%",
"Colic aid* Oral Drops",
"Co-trimoxazole Tablet (80 mg + 400 mg)",
"Co-trimoxazole Tablet (20 mg + 100 mg)",
"Co-trimoxazole Oral Liquid (40 mg + 200 mg)",
"Dextromethorphan Oral Liquid 15 mg/5 ml",
"Diclofenac Tablet 50 mg",
"Dicyclomine Tablet 10 mg",
"Diethylcarbamazine (DEC) Oral Liquid 120 mg/5 ml",
"Diethylcarbamazine (DEC) Tablet 100 mg",
"Domperidone Oral Liquid 1 mg/1 ml",
"Domperidone Tablet 10 mg",
"Doxycycline Capsule 100 mg",
"Enalapril Tablet 5 mg",
"Folic acid Tablet 1 mg",
"Folic acid Tablet 5 mg",
"Framycetin Cream 1%",
"Fluconazole Tablet 100 mg",
"Glimepiride Tablet 2 mg",
"Hydrochlorothiazide Tablet 12.5 mg",
"Hydrochlorothiazide Tablet 25 mg",
"Ibuprofen Tablet 400 mg",
"Ibuprofen Syrup 100 mg/5 ml",
"IFA (Ferrous Salt + Folic acid) Tablet (45 mg + 400 mcg)",
"IFA (Ferrous Salt + Folic acid) Tablet (100 mg + 500 mcg)",
"IFA (Ferrous Salt + Folic acid) Oral Liquid (20 mg + 100 mcg/1 ml)",
"Junior Lanzol* Dispersible Tablet 15 mg",
"Lactulose Oral Liquid 10 g/15 ml",
"Levocetirizine* Tablet 5 mg",
"Levocetirizine* Oral Liquid 2.5 mg/5 ml",
"Levothyroxine Tablet 25 mcg",
"Levothyroxine Tablet 50 mcg",
"Levothyroxine Tablet 100 mcg",
"Metformin Tablet 500 mg",
"Metformin SR* Tablet 500 mg",
"Metronidazole Tablet 200 mg",
"Metronidazole Tablet 400 mg",
"Milk of Magnesia* Oral Liquid 8%",
"Mupirocin Ointment 2%",
"Omeprazole Capsule 20 mg",
"Ondansetron Tablet 4 mg",
"Ondansetron Oral Liquid 2 mg/5 ml",
"Oral Rehydration Salts (ORS, Large)",
"Oral Rehydration Salts (ORS, Small)",
"Paracetamol Oral Drops 100mg/1ml",
"Paracetamol Syrup 125 mg/5ml",
"Paracetamol Syrup 250 mg/5ml",
"Paracetamol Tablet 500 mg",
"Paradichlorobenzene+Chlorbutol+Turpentine Oil+ Lidocaine* Ear Drops (2%+5%+15%+2%)",
"Permethrin Cream 5%",
"Salbutamol Tablet 2 mg",
"Salbutamol Oral Liquid 2 mg/5 ml",
"Saline Nasal Drops 0.65%",
"Silver Sulphadiazine Cream 1%",
"Telmisartan Tablet 40 mg",
"Xylometazoline Nasal Drops 0.05%",
"Xylometazoline Nasal Drops 0.1%",
"Zinc Oxide* Cream 10%",
"Zinc Sulphate Dispersible Tablet 20 mg"
]
