// export default [
//   "Albendazole Tablets 400mg",
//   "Amlodipine Tablets 5 mg",
//   "Amoxycillin Capsules 500 mg",
//   "Amoxycillin Capsules 250mg",
//   "Ascorbic Acid Tablets(Chewable)",
//   "Atenolol Tablets 50 mg",
//   "Bisacodyl Tablet 5 mg",
//   "Calcium gluconate Tablet 500 mg",
//   "Chloroquine phosphateTablet 250 mg",
//   "Chlorpheniramine Maleate Tablets 4 mg",
//   "Clotrimazole Vaginal Tablet 100 mg",
//   "Dexamethasone Tablet 0.5 mg",
//   "Diclofenac Sodium Tablets 50 mg",
//   "Dicyclomine Tablets 20 mg",
//   "Domperidone Tablets 10 mg",
//   "Enalapril Maleate Tablets 5 mg",
//   "Etopyllin with theophylline tablet",
//   "Ferrous salt 20 mg + Folic acid 100 mcg Tablet",
//   "Ferrous salt 100 mg + Folic acid 500 mcg Tablet",
//   "Folic Acid Tablets 5mg",
//   "Ibuprofen Tablets 400mg",
//   "Metformin HCL Tablets 500mg",
//   "Metronidazole Tablets 400mg",
//   "Metronidazole Tablet 200mg",
//   "Norfloxacin Tablets 400mg",
//   "Paracetamol Tablets 500mg",
//   "Primaquine Phosphate Tablets 2.5mg",
//   "Primaquine Phosphate Tablets 7.5mg",
//   "Salbutamol Tablet 4 mg",
//   "Vitamin A Capsules",
//   "Vitamin B Complex Tablets (Therapeutic)",
//   "Azithromycin Tablet 500 mg",
//   "Cefixime Tablet 200 mg",
//   "Asprin (Acetylsalicylic acid) Tablet 75 mg",
//   "Clopidogrel Tablets 75mg",
//   "Zinc Sulphate Dispersible Tablets 20mg",
//   "Atorvastatin Tablet 40 mg",
//   "Bisacodyl Suppository 5 mg",
//   "Azithromycin Tablet 250 mg",
//   "Famotidine Tablets 40mg",
//   "Formoterol & Budesonide Rotacap 6 mcg+ 200 mcg 200mcg",
//   "Montelukast Sodium Tablet 10 mg",
//   "Paracetamol Tablet 650 mg",
//   "Labetalol Tablet 100 mg",
//   "Ferrous salt 60mg + Folic acid 500mcg",
//   "Tablet Diclofenac sodium",
//   "Injection Eteophylline & Theophylline",
//   "Injection Gentamicin Injection 80 mg/ml",
//   "Pralidoxime chloride Injection 25 mg/ml",
//   "Ringer lactate Injection",
//   "Sodium chloride injection",
//   "Sterile Water for Injection (5ml)",
//   "Vitamin B Complex Injection",
//   "Sodium Chloride Inj.(IV use) 100ml",
//   "Albendazole Oral liquid 200 mg/5 ml",
//   "Amoxycillin oral suspension",
//   "Betamethasone Valerate Cream 0.1%",
//   "Cholecalciferol Granules (Vitamin D3)",
//   "Ciprofloxacin Ophthalmic Solution",
//   "Clotrimazole Cream 1%",
//   "Vitamin A Solution Conc. 1 Lac IU/1ml, 100ml",
//   "Bottle Dextromethorphan Syrup 13.5 mg/5 ml",
//   "Domperidone Syrup",
//   "Framycetin Sulphate Skin Cream (30Gm Tube)",
//   "Glycerine Hydrogen peroxide Solution",
//   "Ibuprofen oral Suspension 100 mg/5 ml",
//   "Metronidazole Oral liquid 100 mg/5 ml",
//   "O.R.S.(W.H.O. Formula)",
//   "Paracetamol Syrup 125 mg/5ml",
//   "Povidone iodine Solution 5%",
//   "Povidine lodine (Ointment)",
//   "Povidone lodine Solution 5%W/V(1 Litre)",
//   "Salbutamol Nebulizer Solution",
//   "Salbutamol Syrup 2 mg/5 ml",
//   "Silver sulphadiazine Cream 1%",
//   "Calamine Lotion Neomycin",
//   "Bacitracin & Palymaxin B Oint.",
//   "Azithromycin Oral liquid 200mg/5ml",
//   "Levocetirizine Dihydrochloride Syrup",
//   "Lignocaine Hydrochloride Jelly",
//   "IRON FOLIC ACID (IFA) SYRUP",
//   "Alcoholic Rub Hand Disinfectant 500 ml",
//   "Calcium & Vitamin D3 Suspension 100 ml bottle",
//   "Cefixime syrup",
//   "Xylometazoline Nasal Drops 0.05%",
//   "Disposable Syringe 10 ml(Without Needle)",
//   "Sterile Hypodermic Syringe for Single use Size 2 ml(Without Needle)",
//   "Sterile Hypodermic Syringe for Single use Size: SML(Without Needle)",
//   "Plastic Bags(Yellow)",
//   "Small Plastic Bags(Red)",
//   "Small Plastic Bags(Black)",
//   "Small Surgical Rubber Gloves(Disposable) 6 Inch",
//   "Surgical Rubber Gloves(Disposable) 6.5 Inch",
//   "Surgical Rubber Gloves(Disposable) 7 Inch",
//   "Surgical Rubber Gloves (Disposable) 7.5 Inch",
//   "Surgical Rubber Gloves (Disposable) 8 Inch tab",
//   "metformin 500mg + tab glimeperide 2mg tab",
//   "metformin 500mg + tab glimeperide 1mg Glimepiride Tablet 2 mg",
//   "Metformin Hydrochloride Tablets 500 mg TAB",
//   "GLIPIZIDE 5MG",
//   "Tab Paracetamol 500mg",
//   "Tab Cetrizine 10mg",
//   "Tab Amoxicillin/clavulanic acid 875/125mg",
//   "Cap Omeprazole 20mg",
//   "Tab Dexamethasone 6mg",
//   "Tab Hydrocortisone 10mg",
//   "Tab Prednisolone 20mg",
//   "Tab Methylprednisolone 8mg",
//   "Tab Vitamin C 500mg",
//   "Cholecalciferol Grannules 6000IU",
//   "Tab Metformin 500mg",
//   "Tab Glimepride 2mg",
//   "Tab Glibenclamide 5mg",
//   "Tab Atenolol 50mg",
//   "Tab Amlodepine 5mg",
//   "Tab Enalapril 5mg",
//   "Tab Cefixime 200mg",
//   "Tab Azithromycin 250mg",
//   "Lactulose 250ml bottle",
//   "ORS 21gm sachet",
//   "Tab Doxycycline 100mg",
//   "Syrup Kesol 200ml bottle"
// ];

export default {
    earlyMorning: [
        '1 Glass of water with 1 tablespoon of Methi seeds [soaked overnight]',
        '1 Glass of water with 1 teaspoon of Methi seeds [soaked overnight]',
    ],
    breakfast: [
        'Tea with milk [no sugar]|| चाय [बिना चीनी]',
        'Milk [no sugar]|| दूध [बिना चीनी]',
        'Coffee [no sugar]|| कॉफी [बिना चीनी]',
        'Vegetable poha|| सब्जी पोहा',
        'Vegetable upma|| सब्जी उपमा',
        'Plain paratha [without oil]|| सादा पराठा [बिना तेल के]',
        'Paneer paratha|| पनीर पराठा',
        'Vegetable stuffed paratha [without oil]|| वेजिटेबल स्टफ्ड पराठा [बिना तेल]',
        'Daliya with milk [no sugar]|| दूध के साथ दलिया [बिना चीनी]',
        'Jowar with milk [no sugar]|| दूध के साथ ज्वार [बिना चीनी]',
        'Oats with milk [no sugar]|| दूध के साथ ओट्स [बिना चीनी]',
        'Sabzi [Avoid potato, sweet potato, yam, corn]|| सब्जी',
        'Herbal tea|| औषधिक/हर्बल चाय',
        'Rava Dosa|| रवा दोसा',
        'Rava Idli|| रवा इडली',
        'Onion Tomato Uttappam|| प्याज टमाटर उत्तपम',
        'Red chutney|| लाल चटनी',
        'Besan Cheela|| बेसन चीला',
        'Besan Cheela with vegetables|| सब्जियों के साथ बेसन चीला',
        'Moong dal Cheela|| मूंग दाल चीला',
        'Moong dal Cheela with vegetables|| मूंग दाल चीला सब्जियों के साथ',
        'Cornflakesv मक्कई के भुने हुए आटा',
        'egg [medium size]|| अंडा [मध्यम आकार]',
        'egg [without yellow part; medium size]|| अंडा [पीले भाग के बिना; मध्यम आकार]',
        'Whole wheat bread|| साबुत गेहूँ की ब्रेड',
        'Dhokla [2 big pieces]|| ढोकला [2 बड़े पीस]',
        'Fruit [Avoid banana, grapes, mango, cheeku, jackfruit]|| फल',
        'sambhar|| सांभर',
        'Oats|| ओट्स',
        'Dosa|| डोसा',
        'Curd|| दही',
        'phulkas|| फुल्के',
        'chapatti|| चपाती',
        'Idli|| इडली',
        'Oats Dosa|| ओट्स डोसा',
        'Poha|| पोहा',
        'Upma|| उपमा',
    ],
    midMorning: [
        'Fruit [Avoid banana, grapes, mango, cheeku, jackfruit]|| फल',
        'Buttermilk [No sugar]|| छाछ [बिना चीनी]',
        'Egg [boiled medium size]|| अंडा [उबला हुआ मध्यम आकार का]',
        'Egg [boiled without yellow part; medium size]|| अंडा [बिना पीले भाग के उबला हुआ; मध्यम आकार]',
        'Nuts [Avoid raisins/ dates/ cashewnuts]|| मेवे/नट्स  [काजू /खजूरसे परहेज करें]',
        'Cucumber sticks|| ककड़ी',
        'sprouts with onion and tomato|| प्याज और टमाटर के साथ स्प्राउट्स'
    ],
    lunch: [
        'parataha without oil|| बिना तेल के पराठा',
        'Vegetable paratha without oil [Avoid carrot, potato, corn]|| बिना तेल के सब्जी पराठा [गाजर, आलू, मक्का से परहेज़ करें]',
        'Thepla [medium size]|| थेपला [मध्यम आकार]',
        'Jowar bhakri|| ज्वार भाकरी',
        'Bajra bhakri|| बाजरा भाकरी',
        'Soya bhakri|| सोया भाकरी',
        'Ragi Bhakri|| रागी भाकरी',
        'Jowar + Wheat chapatti [1:1]|| ज्वार + गेहूं की चपाती [1:1]',
        'Bajra + Wheat chapatti [1:1]|| बाजरा + गेहूं की चपाती [1:1]',
        'Ragi + Wheat chapatti [1:1]|| रागी + गेहूं की चपाती [1:1]',
        'Besan Cheela|| बेसन चीला',
        'Moong dal cheela|| मूंग दाल चीला',
        'Paneer paratha without oil|| बिना तेल के पनीर पराठा',
        'Sabzi [Avoid potato, corn|| yam, sweet potato, carrot, beetroot], सब्जी [आलू, मक्का, रतालू, शकरकंद, गाजर, चुकन्दर से परहेज़ करें]',
        'Moong Dal Pulaov मूंग दाल पुलो',
        'Vegetble pulao|| सब्जी पुलाव',
        'Vegetable khichdi|| सब्जी खिचड़ी',
        'Moong Dal|| मूंग दाल',
        'Tuur Dal|| तूर डाली',
        'Chicken Biryani|| चिकन बिरयानी',
        'Chicken piece [Medium piece]|| चिकन [मध्यम टुकड़ा]',
        'Fish [medium piece]|| मछली [मध्यम टुकड़ा]',
        'Mutton [Avoid beef]|| मटन [बीफ से बचें]',
        'White beans|| सफेद सेम',
        'Red Beans|| राजमा',
        'Sprouts salad|| अंकुरित सलाद',
        'Cabbage salad|| बंदगोभी सलाद',
        'Chicken salad with vegetables|| सब्जियों के साथ चिकन सलाद',
        'Paneer gravy|| पनीर ग्रेवी',
        'Roasted paneer|| चीज़ भुना हुआ',
        'Paneer salad|| चीज़ सलाद',
        'Beans salad|| बीन्स सलाद',
        'Soy Chapatti|| सोया चपाती',
        'Chapatti|| चपाती',
        'phulkas|| फुल्के',
        'Kadhi|| कढ़ी/सालन',
        'Khichdi|| खिचड़ी',
        'Salad|| सलाद',
        'Beans|| फलियाँ',
        'Sprouts|| अंकुरित',
        'Rajma|| राजमा',
        'Chole, छोले',
        'Curd|| दही',
        'Buttermilk|| छाछ',
        'Rice|| चावल',
        'Dal|| दल',
    ],
    eveningSnack: [
        'Roasted Chana|| भुना हुआ चना',
        'Roasted Makhana|| भुना हुआ मखाना',
        'Poha chevda|| पोहा चेवड़ा',
        'Khakra [non fried]|| खाकरा [बिना तली हुई]',
        'Bajra chivda|| बाजरा चिवड़ा',
        'Sprouts salad|| अंकुरित सलाद',
        'Boiled sprouts|| उबले हुए स्प्राउट्स',
        'Jowar with milk|| दूध के साथ ज्वार',
        'Bajra with milk|| दूध के साथ बाजरा',
        'Oats with milk|| दूध के साथ ओट्स',
        'Vegetable poha|| सब्जी पोहा',
        'Vegetable Upma|| सब्जी उपमा',
        'Tea with milk [No Sugar] [without sugar]|| चाय [बिना चीनी]',
        'Coffee [without sugar]|| कॉफी [बिना चीनी]',
        'Herbal tea [without sugar]|| हर्बल चाय [बिना चीनी]',
        'Milk [without sugar]|| दूध [बिना चीनी]',
    ],
    dinner: [
        'parataha without oil|| बिना तेल के पराठा',
        'Vegetable paratha without oil [Avoid carrot, potato, corn]|| बिना तेल के सब्जी पराठा [गाजर, आलू, मक्का से परहेज़ करें]',
        'Thepla [medium size]|| थेपला [मध्यम आकार]',
        'Jowar bhakri|| ज्वार भाकरी',
        'Bajra bhakri|| बाजरा भाकरी',
        'Soya bhakri|| सोया भाकरी',
        'Ragi Bhakri|| रागी भाकरी',
        'Jowar + Wheat chapatti [1:1]|| ज्वार + गेहूं की चपाती [1:1]',
        'Bajra + Wheat chapatti [1:1]|| बाजरा + गेहूं की चपाती [1:1]',
        'Ragi + Wheat chapatti [1:1]|| रागी + गेहूं की चपाती [1:1]',
        'Besan Cheela|| बेसन चीला',
        'Moong dal cheela|| मूंग दाल चीला',
        'Paneer paratha without oil|| बिना तेल के पनीर पराठा',
        'Sabzi [Avoid potato, corn, yam, sweet potato, carrot, beetroot]|| सब्जी [आलू, मक्का, रतालू, शकरकंद, गाजर, चुकन्दर से परहेज़ करें]',
        'Vegetble pulao|| सब्जी पुलाव',
        'Vegetable khichdi|| सब्जी खिचड़ी',
        'Moong Dal|| मूंग दाल',
        'Tuur Dal|| तूर डाली',
        'Chicken Biryani|| चिकन बिरयानी',
        'Chicken [Medium piece]|| चिकन [मध्यम टुकड़ा]',
        'Fish [medium piece]|| मछली [मध्यम टुकड़ा]',
        'Mutton [Avoid beef]|| मटन [बीफ से बचें]',
        'White beans|| सफेद सेम',
        'Red Beans|| राजमा',
        'Sprouts salad|| अंकुरित सलाद',
        'Cabbage salad|| बंदगोभी सलाद',
        'Chicken salad with vegetables|| सब्जियों के साथ चिकन सलाद',
        'Paneer gravy|| पनीर की ग्रेवी',
        'Paneer roasted|| पनीर भुना हुआ',
        'Paneer salad|| पनीर सलाद',
        'Beans salad|| बीन्स सलाद',
        'Soy Chapatti|| सोया चपाती',
        'Moong Dal Pulo|| मूंग दाल पुलो',
        'Chapatti|| चपाती',
        'phulkas|| फुल्के',
        'Beans|| फलियाँ',
        'Sprouts|| अंकुरित',
        'Rajma|| राजमा',
        'Chole|| छोले',
        'Salad|| सलाद',
        'Curd|| दही',
        'Buttermilk|| छाछ',
        'Brown Rice|| चावल',
        'Dal|| दल',
        'Kadhi|| कढ़ी',
        'Khichdi|| खिचड़ी',
    ],
    bedTime: [
        'Milk [no sugar]|| दूध [बिना चीनी]',
        'Protein supplement|| प्रोटीन सप्लीमेंट',
        'Fruit [Avoid banana, grapes, mango, cheeku, jackfruit]|| फल',
        'Nuts [Avoid raisins/ dates/ cashewnuts]|| मेवे/नट्स  [काजू /खजूरसे परहेज करें]',
        '1 Glass of water with 1 tablespoon of Methi seeds [soaked overnight]|| 1 गिलास पानी में 1 बड़ा चम्मच मेथी के बीज [रात भर भीगे हुए]',
        '1 Glass of water with 1 teaspoon of Methi seeds [soaked overnight]|| 1 गिलास पानी में 1 चम्मच मेथी दाना [रात भर भिगोया हुआ]'
    ]
}