export const conversations = [
    {
      name: 'Hitesh Shah',
      latestMessage: 'CHW: Please take a look at...',
      latestMessageRead: false,
      profileLink:'/assets/icons/message/Frame1.png',
      messages: [
        { id: 1, body: 'Hi! How is patient feeling now?', me: true },
        { id: 2, body: 'The patient was not feeling good for 2-3 days but lately the patient is doing well.', me: false },
        { id: 3, body: 'The patient want to thank you for giving such a good treatment. Also I will send her reports with you as soon as I receive it.', me: false },
        { id: 4, body: 'Great to hear. Keep me posted on the patient.', me: true },
      ],
    },
    {
      name: 'Muskan Kala',
      latestMessage: 'I’ve sent the prescription...',
      latestMessageRead: true,
      profileLink:'/assets/icons/message/Frame2608562.png',
      messages: [
        { id: 1, body: 'Hi! How is patient feeling now?', me: true },
        { id: 2, body: 'The patient was not feeling good for 2-3 days but lately the patient is doing well.', me: false },
        { id: 3, body: 'The patient want to thank you for giving such a good treatment. Also I will send her reports with you as soon as I receive it.', me: false },
        { id: 4, body: 'Great to hear. Keep me posted on the patient.', me: true },
      ],
    },
    {
      name: 'Rehman Sheikh',
      latestMessage: 'CHW: I will take the follow...',
      latestMessageRead: false,
      profileLink:'/assets/icons/message/Frame2608562(1).png',
      messages: [
        { id: 1, body: 'Hi! How is patient feeling now?', me: true },
        { id: 2, body: 'The patient was not feeling good for 2-3 days but lately the patient is doing well.', me: false },
        { id: 3, body: 'The patient want to thank you for giving such a good treatment. Also I will send her reports with you as soon as I receive it.', me: false },
        { id: 4, body: 'Great to hear. Keep me posted on the patient.', me: true },
      ],
    },
    {
      name: 'Jason Sullivan',
      latestMessage: 'CHW: Please taka look at...',
      latestMessageRead: true,
      profileLink:'/assets/icons/message/Frame2608562(2).png',
      messages: [
        { id: 1, body: 'Hi! How is patient feeling now?', me: true },
        { id: 2, body: 'The patient was not feeling good for 2-3 days but lately the patient is doing well.', me: false },
        { id: 3, body: 'The patient want to thank you for giving such a good treatment. Also I will send her reports with you as soon as I receive it.', me: false },
        { id: 4, body: 'Great to hear. Keep me posted on the patient.', me: true },
      ],
    },
    {
      name: 'Mehek Sharma',
      latestMessage: 'Please send the reports.',
      latestMessageRead: false,
      profileLink:'/assets/icons/message/Frame1.png',
      messages: [
        { id: 1, body: 'Hi! How is patient feeling now?', me: true },
        { id: 2, body: 'The patient was not feeling good for 2-3 days but lately the patient is doing well.', me: false },
        { id: 3, body: 'The patient want to thank you for giving such a good treatment. Also I will send her reports with you as soon as I receive it.', me: false },
        { id: 4, body: 'Great to hear. Keep me posted on the patient.', me: true },
      ],
    },
    {
      name: 'Karan chandhok',
      latestMessage: "Can I get patient’s number",
      latestMessageRead: false,
      profileLink:'/assets/icons/message/Frame1.png',
      messages: [
        { id: 1, body: 'Hi! How is patient feeling now?', me: true },
        { id: 2, body: 'The patient was not feeling good for 2-3 days but lately the patient is doing well.', me: false },
        { id: 3, body: 'The patient want to thank you for giving such a good treatment. Also I will send her reports with you as soon as I receive it.', me: false },
        { id: 4, body: 'Great to hear. Keep me posted on the patient.', me: true },
      ],
    },
    {
      name: 'Tom',
      latestMessage: 'I see',
      latestMessageRead: true,
      profileLink:'/assets/icons/message/Frame2608562(3).png',
      messages: [
        { id: 1, body: 'Hi! How is patient feeling now?', me: true },
        { id: 2, body: 'The patient was not feeling good for 2-3 days but lately the patient is doing well.', me: false },
        { id: 3, body: 'The patient want to thank you for giving such a good treatment. Also I will send her reports with you as soon as I receive it.', me: false },
        { id: 4, body: 'Great to hear. Keep me posted on the patient.', me: true },
      ],
    },
    {
      name: 'Piya Ahuja',
      latestMessage: 'OMG',
      latestMessageRead: false,
      profileLink:'/assets/icons/message/Frame1.png',
      messages: [
        { id: 1, body: 'Hi! How is patient feeling now?', me: true },
        { id: 2, body: 'The patient was not feeling good for 2-3 days but lately the patient is doing well.', me: false },
        { id: 3, body: 'The patient want to thank you for giving such a good treatment. Also I will send her reports with you as soon as I receive it.', me: false },
        { id: 4, body: 'Great to hear. Keep me posted on the patient.', me: true },
      ],
    },
    {
      name: 'Grey',
      latestMessage: 'Oh No',
      latestMessageRead: false,
      profileLink:'/assets/icons/message/Frame1.png',
      messages: [
        { id: 1, body: 'Hi! How is patient feeling now?', me: true },
        { id: 2, body: 'The patient was not feeling good for 2-3 days but lately the patient is doing well.', me: false },
        { id: 3, body: 'The patient want to thank you for giving such a good treatment. Also I will send her reports with you as soon as I receive it.', me: false },
        { id: 4, body: 'Great to hear. Keep me posted on the patient.', me: true },
      ],
    },
    {
      name: 'Jill',
      latestMessage: 'Thanks',
      latestMessageRead: true,
      profileLink:'/assets/icons/message/Frame1.png',
      messages: [
        { id: 1, body: 'Hi! How is patient feeling now?', me: true },
        { id: 2, body: 'The patient was not feeling good for 2-3 days but lately the patient is doing well.', me: false },
        { id: 3, body: 'The patient want to thank you for giving such a good treatment. Also I will send her reports with you as soon as I receive it.', me: false },
        { id: 4, body: 'Great to hear. Keep me posted on the patient.', me: true },
      ],
    },
    {
      name: 'Blue',
      latestMessage: 'Take care',
      latestMessageRead: false,
      profileLink:'/assets/icons/message/Frame1.png',
      messages: [
        { id: 1, body: 'Hi! How is patient feeling now?', me: true },
        { id: 2, body: 'The patient was not feeling good for 2-3 days but lately the patient is doing well.', me: false },
        { id: 3, body: 'The patient want to thank you for giving such a good treatment. Also I will send her reports with you as soon as I receive it.', me: false },
        { id: 4, body: 'Great to hear. Keep me posted on the patient.', me: true },
      ],
    },
    {
      name: 'King',
      latestMessage: 'I am coming now',
      latestMessageRead: false,
      profileLink:'/assets/icons/message/Frame1.png',
      messages: [
        { id: 1, body: 'Hi! How is patient feeling now?', me: true },
        { id: 2, body: 'The patient was not feeling good for 2-3 days but lately the patient is doing well.', me: false },
        { id: 3, body: 'The patient want to thank you for giving such a good treatment. Also I will send her reports with you as soon as I receive it.', me: false },
        { id: 4, body: 'Great to hear. Keep me posted on the patient.', me: true },
      ],
    },
    {
      name: 'Kong',
      latestMessage: 'Good Morning!',
      latestMessageRead: true,
      profileLink:'/assets/icons/message/Frame1.png',
      messages: [
        { id: 1, body: 'Hi! How is patient feeling now?', me: true },
        { id: 2, body: 'The patient was not feeling good for 2-3 days but lately the patient is doing well.', me: false },
        { id: 3, body: 'The patient want to thank you for giving such a good treatment. Also I will send her reports with you as soon as I receive it.', me: false },
        { id: 4, body: 'Great to hear. Keep me posted on the patient.', me: true },
      ],
    },
    {
      name: 'Rock',
      latestMessage: 'Good Morning!',
      latestMessageRead: true,
      profileLink:'/assets/icons/message/Frame1.png',
      messages: [
        { id: 1, body: 'Hi! How is patient feeling now?', me: true },
        { id: 2, body: 'The patient was not feeling good for 2-3 days but lately the patient is doing well.', me: false },
        { id: 3, body: 'The patient want to thank you for giving such a good treatment. Also I will send her reports with you as soon as I receive it.', me: false },
        { id: 4, body: 'Great to hear. Keep me posted on the patient.', me: true },
      ],
    },
  ];
